version: 0.0
os: linux
files:
   - source/
   destination: /var/www/html
hooks:
    AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root
  deployment:
  revision:
    revisionType: S3
    s3Location:
      bucket: simran90215
      key: aadiba/demo-app-build.zip
